
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.1.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace AutoSetup {
    using System;
    using Terminal.Gui;
    
    
    public partial class Locker : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme alertColors;

        private Terminal.Gui.ColorScheme defaultColors;
        
        private Terminal.Gui.FrameView frameView;
        
        private Terminal.Gui.Label tryInfo;
        
        private Terminal.Gui.TextField passInput;
        
        private Terminal.Gui.Button passCheck;
        
        private void InitializeComponent() {
            this.passCheck = new Terminal.Gui.Button();
            this.passInput = new Terminal.Gui.TextField();
            this.tryInfo = new Terminal.Gui.Label();
            this.frameView = new Terminal.Gui.FrameView();
            this.defaultColors = new Terminal.Gui.ColorScheme();
            this.defaultColors.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.defaultColors.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.defaultColors.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.DarkGray);
            this.defaultColors.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.defaultColors.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.alertColors = new Terminal.Gui.ColorScheme();
            this.alertColors.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightYellow, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.ColorScheme = this.defaultColors;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.frameView.Width = 35;
            this.frameView.Height = 11;
            this.frameView.X = Pos.Center();
            this.frameView.Y = Pos.Center();
            this.frameView.Visible = true;
            this.frameView.Data = "frameView";
            this.frameView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameView.Border.Effect3D = false;
            this.frameView.Border.Effect3DBrush = null;
            this.frameView.Border.DrawMarginFrame = true;
            this.frameView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView.Title = "Введите пароль...";
            this.Add(this.frameView);
            this.tryInfo.Width = 25;
            this.tryInfo.Height = 1;
            this.tryInfo.X = Pos.Center();
            this.tryInfo.Y = 1;
            this.tryInfo.Visible = true;
            this.tryInfo.ColorScheme = this.alertColors;
            this.tryInfo.Data = "tryInfo";
            this.tryInfo.Text = "У вас осталось 3 попытки";
            this.tryInfo.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.frameView.Add(this.tryInfo);
            this.passInput.Width = 15;
            this.passInput.Height = 1;
            this.passInput.X = Pos.Center();
            this.passInput.Y = Pos.Center();
            this.passInput.Visible = true;
            this.passInput.Secret = true;
            this.passInput.Data = "passInput";
            this.passInput.Text = "";
            this.passInput.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView.Add(this.passInput);
            this.passCheck.Width = 14;
            this.passCheck.Height = 1;
            this.passCheck.X = Pos.Center();
            this.passCheck.Y = Pos.AnchorEnd(2);
            this.passCheck.Visible = true;
            this.passCheck.Data = "passCheck";
            this.passCheck.Text = "Проверить";
            this.passCheck.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.passCheck.IsDefault = true;
            this.frameView.Add(this.passCheck);
        }
    }
}
